import React from 'react';

export default function Game() {
  return (
    <div className='gameContainer'>
      <div className='p1Board'>
        <div className='emptysquare' id='square-0'></div>
        <div className='emptysquare' id='square-1'></div>
        <div className='emptysquare' id='square-2'></div>
        <div className='emptysquare' id='square-3'></div>
        <div className='emptysquare' id='square-4'></div>
        <div className='emptysquare' id='square-5'></div>
        <div className='emptysquare' id='square-6'></div>
        <div className='emptysquare' id='square-7'></div>
        <div className='emptysquare' id='square-8'></div>
        <div className='emptysquare' id='square-9'></div>
        <div className='emptysquare' id='square-10'></div>
        <div className='emptysquare' id='square-11'></div>
        <div className='emptysquare' id='square-12'></div>
        <div className='emptysquare' id='square-13'></div>
        <div className='emptysquare' id='square-14'></div>
        <div className='emptysquare' id='square-15'></div>
        <div className='emptysquare' id='square-16'></div>
        <div className='emptysquare' id='square-17'></div>
        <div className='emptysquare' id='square-18'></div>
        <div className='emptysquare' id='square-19'></div>
        <div className='emptysquare' id='square-20'></div>
        <div className='emptysquare' id='square-21'></div>
        <div className='emptysquare' id='square-22'></div>
        <div className='emptysquare' id='square-23'></div>
        <div className='emptysquare' id='square-24'></div>
        <div className='emptysquare' id='square-25'></div>
        <div className='emptysquare' id='square-26'></div>
        <div className='emptysquare' id='square-27'></div>
        <div className='emptysquare' id='square-28'></div>
        <div className='emptysquare' id='square-29'></div>
        <div className='emptysquare' id='square-30'></div>
        <div className='emptysquare' id='square-31'></div>
        <div className='emptysquare' id='square-32'></div>
        <div className='emptysquare' id='square-33'></div>
        <div className='emptysquare' id='square-34'></div>
        <div className='emptysquare' id='square-35'></div>
        <div className='emptysquare' id='square-36'></div>
        <div className='emptysquare' id='square-37'></div>
        <div className='emptysquare' id='square-38'></div>
        <div className='emptysquare' id='square-39'></div>
        <div className='emptysquare' id='square-40'></div>
        <div className='emptysquare' id='square-41'></div>
        <div className='emptysquare' id='square-42'></div>
        <div className='emptysquare' id='square-43'></div>
        <div className='emptysquare' id='square-44'></div>
        <div className='emptysquare' id='square-45'></div>
        <div className='emptysquare' id='square-46'></div>
        <div className='emptysquare' id='square-47'></div>
        <div className='emptysquare' id='square-48'></div>
        <div className='emptysquare' id='square-49'></div>
        <div className='emptysquare' id='square-50'></div>
        <div className='emptysquare' id='square-51'></div>
        <div className='emptysquare' id='square-52'></div>
        <div className='emptysquare' id='square-53'></div>
        <div className='emptysquare' id='square-54'></div>
        <div className='emptysquare' id='square-55'></div>
        <div className='emptysquare' id='square-56'></div>
        <div className='emptysquare' id='square-57'></div>
        <div className='emptysquare' id='square-58'></div>
        <div className='emptysquare' id='square-59'></div>
        <div className='emptysquare' id='square-60'></div>
        <div className='emptysquare' id='square-61'></div>
        <div className='emptysquare' id='square-62'></div>
        <div className='emptysquare' id='square-63'></div>
        <div className='emptysquare' id='square-64'></div>
        <div className='emptysquare' id='square-65'></div>
        <div className='emptysquare' id='square-66'></div>
        <div className='emptysquare' id='square-67'></div>
        <div className='emptysquare' id='square-68'></div>
        <div className='emptysquare' id='square-69'></div>
        <div className='emptysquare' id='square-70'></div>
        <div className='emptysquare' id='square-71'></div>
        <div className='emptysquare' id='square-72'></div>
        <div className='emptysquare' id='square-73'></div>
        <div className='emptysquare' id='square-74'></div>
        <div className='emptysquare' id='square-75'></div>
        <div className='emptysquare' id='square-76'></div>
        <div className='emptysquare' id='square-77'></div>
        <div className='emptysquare' id='square-78'></div>
        <div className='emptysquare' id='square-79'></div>
        <div className='emptysquare' id='square-80'></div>
        <div className='emptysquare' id='square-81'></div>
        <div className='emptysquare' id='square-82'></div>
        <div className='emptysquare' id='square-83'></div>
        <div className='emptysquare' id='square-84'></div>
        <div className='emptysquare' id='square-85'></div>
        <div className='emptysquare' id='square-86'></div>
        <div className='emptysquare' id='square-87'></div>
        <div className='emptysquare' id='square-88'></div>
        <div className='emptysquare' id='square-89'></div>
        <div className='emptysquare' id='square-90'></div>
        <div className='emptysquare' id='square-91'></div>
        <div className='emptysquare' id='square-92'></div>
        <div className='emptysquare' id='square-93'></div>
        <div className='emptysquare' id='square-94'></div>
        <div className='emptysquare' id='square-95'></div>
        <div className='emptysquare' id='square-96'></div>
        <div className='emptysquare' id='square-97'></div>
        <div className='emptysquare' id='square-98'></div>
        <div className='emptysquare' id='square-99'></div>
      </div>
      <div className='p2Board'>
        <div className='emptysquare' id='square-0'></div>
        <div className='emptysquare' id='square-1'></div>
        <div className='emptysquare' id='square-2'></div>
        <div className='emptysquare' id='square-3'></div>
        <div className='emptysquare' id='square-4'></div>
        <div className='emptysquare' id='square-5'></div>
        <div className='emptysquare' id='square-6'></div>
        <div className='emptysquare' id='square-7'></div>
        <div className='emptysquare' id='square-8'></div>
        <div className='emptysquare' id='square-9'></div>
        <div className='emptysquare' id='square-10'></div>
        <div className='emptysquare' id='square-11'></div>
        <div className='emptysquare' id='square-12'></div>
        <div className='emptysquare' id='square-13'></div>
        <div className='emptysquare' id='square-14'></div>
        <div className='emptysquare' id='square-15'></div>
        <div className='emptysquare' id='square-16'></div>
        <div className='emptysquare' id='square-17'></div>
        <div className='emptysquare' id='square-18'></div>
        <div className='emptysquare' id='square-19'></div>
        <div className='emptysquare' id='square-20'></div>
        <div className='emptysquare' id='square-21'></div>
        <div className='emptysquare' id='square-22'></div>
        <div className='emptysquare' id='square-23'></div>
        <div className='emptysquare' id='square-24'></div>
        <div className='emptysquare' id='square-25'></div>
        <div className='emptysquare' id='square-26'></div>
        <div className='emptysquare' id='square-27'></div>
        <div className='emptysquare' id='square-28'></div>
        <div className='emptysquare' id='square-29'></div>
        <div className='emptysquare' id='square-30'></div>
        <div className='emptysquare' id='square-31'></div>
        <div className='emptysquare' id='square-32'></div>
        <div className='emptysquare' id='square-33'></div>
        <div className='emptysquare' id='square-34'></div>
        <div className='emptysquare' id='square-35'></div>
        <div className='emptysquare' id='square-36'></div>
        <div className='emptysquare' id='square-37'></div>
        <div className='emptysquare' id='square-38'></div>
        <div className='emptysquare' id='square-39'></div>
        <div className='emptysquare' id='square-40'></div>
        <div className='emptysquare' id='square-41'></div>
        <div className='emptysquare' id='square-42'></div>
        <div className='emptysquare' id='square-43'></div>
        <div className='emptysquare' id='square-44'></div>
        <div className='emptysquare' id='square-45'></div>
        <div className='emptysquare' id='square-46'></div>
        <div className='emptysquare' id='square-47'></div>
        <div className='emptysquare' id='square-48'></div>
        <div className='emptysquare' id='square-49'></div>
        <div className='emptysquare' id='square-50'></div>
        <div className='emptysquare' id='square-51'></div>
        <div className='emptysquare' id='square-52'></div>
        <div className='emptysquare' id='square-53'></div>
        <div className='emptysquare' id='square-54'></div>
        <div className='emptysquare' id='square-55'></div>
        <div className='emptysquare' id='square-56'></div>
        <div className='emptysquare' id='square-57'></div>
        <div className='emptysquare' id='square-58'></div>
        <div className='emptysquare' id='square-59'></div>
        <div className='emptysquare' id='square-60'></div>
        <div className='emptysquare' id='square-61'></div>
        <div className='emptysquare' id='square-62'></div>
        <div className='emptysquare' id='square-63'></div>
        <div className='emptysquare' id='square-64'></div>
        <div className='emptysquare' id='square-65'></div>
        <div className='emptysquare' id='square-66'></div>
        <div className='emptysquare' id='square-67'></div>
        <div className='emptysquare' id='square-68'></div>
        <div className='emptysquare' id='square-69'></div>
        <div className='emptysquare' id='square-70'></div>
        <div className='emptysquare' id='square-71'></div>
        <div className='emptysquare' id='square-72'></div>
        <div className='emptysquare' id='square-73'></div>
        <div className='emptysquare' id='square-74'></div>
        <div className='emptysquare' id='square-75'></div>
        <div className='emptysquare' id='square-76'></div>
        <div className='emptysquare' id='square-77'></div>
        <div className='emptysquare' id='square-78'></div>
        <div className='emptysquare' id='square-79'></div>
        <div className='emptysquare' id='square-80'></div>
        <div className='emptysquare' id='square-81'></div>
        <div className='emptysquare' id='square-82'></div>
        <div className='emptysquare' id='square-83'></div>
        <div className='emptysquare' id='square-84'></div>
        <div className='emptysquare' id='square-85'></div>
        <div className='emptysquare' id='square-86'></div>
        <div className='emptysquare' id='square-87'></div>
        <div className='emptysquare' id='square-88'></div>
        <div className='emptysquare' id='square-89'></div>
        <div className='emptysquare' id='square-90'></div>
        <div className='emptysquare' id='square-91'></div>
        <div className='emptysquare' id='square-92'></div>
        <div className='emptysquare' id='square-93'></div>
        <div className='emptysquare' id='square-94'></div>
        <div className='emptysquare' id='square-95'></div>
        <div className='emptysquare' id='square-96'></div>
        <div className='emptysquare' id='square-97'></div>
        <div className='emptysquare' id='square-98'></div>
        <div className='emptysquare' id='square-99'></div>
      </div>
    </div>
  );
}
